### ISSUE TITLE
Implement the adding student_to_roster funcitonality 

### ISSUE THREAD

**Issue by jjames1011** [jjames1011/attendenceapp#42]
Currently there is no way within the UI to add a student to a roster. on the single_roster.html page add a 'add student button'. Also get rid of the 'add students to roster in the navbar' for this should only be accessible through a specific roster page

**Comment by dpryor67** [comment]
Hi Jonathan - there is a link to add student to roster on the single_roster template. That was part of what I did when I updated the functionality of adding a student to a roster.

**Comment by jjames1011** [comment]
Great thanks for letting me know!
