### ISSUE TITLE
Add a submit button to single_session.html

### ISSUE THREAD

**Issue by jjames1011** [jjames1011/attendenceapp#45]
Currently there is no way to submit the data of the single_session.html page to the database.

**Comment by dpryor67** [comment]
Where is this supposed to submit to, exactly?

**Comment by thaindq** [comment]
@dpryor67 submission will update data in Attendence table

**Comment by dpryor67** [comment]
@thaindq I think I phrased my question wrong - I meant, what route is this button supposed to post to? There doesn't appear to be a handler for it, or for any attendance related things.

**Comment by jjames1011** [comment]
Well I never created a route handler to deal with a session table because that was a feature that you implemented and so I was thinking it would probably be best to have you implement the route handler as well so that it works the way you were visioning. @thaindq

**Comment by dpryor67** [comment]
I'm happy to turn it over to @thaindq, if you want it. I took a look at the sessions stuff and didn't really understand what data the forms were even asking the user to input... so perhaps I'm not the best person to jump into this if it's going to take more effort than linking up a button.

**Comment by thaindq** [comment]
Surely I can take over this issue. One question: what other information should the Attendence table store, or just check-in & check-out time are enough?

**Comment by jjames1011** [comment]
Yeah and maybe the date.
