### ISSUE TITLE
Single session page submit button

### ISSUE THREAD

**Issue by dpryor67** [jjames1011/attendenceapp#65]
On the single session page, once you click the submit button the times are updated in the check-in/check-out fields, but it's not clear where the user should go from there, since the submit button doesn't send you to another page. Maybe redirect to the single roster page?

**Comment by thaindq** [comment]
I don't think this is a bug. Wherever users decide to go next is up to them. Just updating the time to let users know that students have been checked in/out is enough. What if they want to check in/out another student?

**Comment by dpryor67** [comment]
That's a fair point.... I forgot that you can stay on that page and update multiple students. But I feel it's misleading to have a submit button and nothing else, because eventually you'll check in everyone and then it's not clear why the button is still there and if it still does anything.

**Comment by thaindq** [comment]
@dpryor67 in that case, do you have any suggestion to improve user experience?

**Comment by dpryor67** [comment]
@thaindq Perhaps we could change the text on the submit button to be more specific - like "Update Attendance" - and then put a second button or a link nearby to return to the roster page or the list of rosters, perhaps with some instructions like, "Finished updating attendance? Click here to return to the main page."
